// Builds playground/skin/test-skin.css, the stylesheet of the browser tests.
//
//   theme.css         the theme the shadcn-vue CLI wrote (`shadcn-vue init`,
//                     style reka-nova, base color neutral). Not edited by hand:
//                     every color and radius comes from it.
//   mapping.css       the table's DOM contract mapped onto shadcn-vue class
//                     strings with `@apply`. It is written into
//                     `@layer components`, so a Tailwind utility on a page
//                     overrides it (see `buildSkin`).
//
//   node playground/skin/gen-skin.ts          write test-skin.css
//   node playground/skin/gen-skin.ts --check  fail when test-skin.css is stale
//
// Parts of the CLI output are replaced on purpose:
//   - the Google Fonts `@import url(...)`: tests must not need the network;
//   - `shadcn-vue/tailwind.css`: the CLI writes that import, but the package
//     ships no such file. The same file lives in the `shadcn` package;
//   - the dark theme: the CLI scopes it to a `.dark` class. The skin follows
//     the OS instead (`prefers-color-scheme`) and lets the page override it
//     with `data-theme="light"` or `data-theme="dark"` on <html>. The dark
//     tokens are still the CLI's own, copied from its `.dark` block.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const read = (path: string) => readFileSync(path, 'utf8').replace(/\r\n/g, '\n')

export const skinPath = join(here, 'test-skin.css')

const DARK_VARIANT = '@custom-variant dark (&:is(.dark *));'
const DARK_BLOCK = /^\.dark \{\n([\s\S]*?)\n\}/m

// `dark:` utilities and the dark tokens, keyed to the OS unless the page says
// otherwise (the light override wins over the OS, the dark one over a light OS).
const themed = (theme: string): string => {
  const block = DARK_BLOCK.exec(theme)
  if (!theme.includes(DARK_VARIANT) || !block) {
    throw new Error(
      'theme.css no longer has the `.dark` variant and block gen-skin rewrites.'
    )
  }
  const tokens = block[1]
  const indent = (text: string, spaces: number) =>
    text
      .split('\n')
      .map(line => ' '.repeat(spaces) + line.trim())
      .join('\n')
  const light = ':root:not([data-theme="light"])'
  const variant = [
    '@custom-variant dark {',
    '  @media (prefers-color-scheme: dark) {',
    `    &:where(${light} *) {`,
    '      @slot;',
    '    }',
    '  }',
    '  &:where([data-theme="dark"], [data-theme="dark"] *) {',
    '    @slot;',
    '  }',
    '}'
  ].join('\n')
  const dark = [
    ':root {',
    '  color-scheme: light;',
    '}',
    '',
    '@media (prefers-color-scheme: dark) {',
    `  ${light} {`,
    '    color-scheme: dark;',
    indent(tokens, 4),
    '  }',
    '}',
    '',
    ':root[data-theme="dark"] {',
    '  color-scheme: dark;',
    indent(tokens, 2),
    '}'
  ].join('\n')
  return theme
    .replace(DARK_VARIANT, () => variant)
    .replace(DARK_BLOCK, () => dark)
}

export const buildSkin = (): string => {
  const theme = themed(
    read(join(here, 'theme.css'))
      .replace(/^@import[^\n]*\n/gm, '')
      .trim()
  )
  const mapping = read(join(here, 'mapping.css')).trim()
  return [
    '/* Test-only skin. Generated by playground/skin/gen-skin.ts; do not edit. */',
    '@import "tailwindcss";',
    '@import "tw-animate-css";',
    '@import "shadcn/tailwind.css";',
    '',
    theme,
    '',
    '/* ==== mapping.css, in the components layer ==== */',
    // A rule outside every layer beats all layers, Tailwind's `utilities`
    // included, so a utility class on a page ("w-max" on a wrapper that
    // reaches `.qt-table`) would lose to the mapping. In `components` the
    // utilities win, as they do over any component class.
    '@layer components {',
    mapping,
    '}',
    ''
  ].join('\n')
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  if (process.argv.includes('--check')) {
    let current = ''
    try {
      current = read(skinPath)
    } catch {
      // A missing file counts as stale.
    }
    if (current !== buildSkin()) {
      console.error(
        'test-skin.css is stale. Run `node playground/skin/gen-skin.ts` and commit it.'
      )
      process.exit(1)
    }
    console.log('test-skin.css is up to date')
  } else {
    writeFileSync(skinPath, buildSkin())
    console.log('wrote playground/skin/test-skin.css')
  }
}
