import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

import { cursorDirections, filterConditions, sortDirections } from '../src'

// The checked-in schema is generated by scripts/gen-schema.mjs and CI runs
// `pnpm schema:check`. These tests tie its vocabularies to the TypeScript
// constants and pin its shape.
interface Definition {
  enum?: string[]
  properties?: Record<string, Definition>
  required?: string[]
  not?: unknown
  additionalProperties?: unknown
  minLength?: number
}

const schema = JSON.parse(
  readFileSync(join(import.meta.dirname, '..', 'query.schema.json'), 'utf8')
) as { oneOf: unknown[]; $defs: Record<string, Definition> }
const defs = schema.$defs

describe('query.schema.json', () => {
  it('lists the conditions and directions of the protocol', () => {
    expect(defs.FilterCondition.enum).toEqual([...filterConditions])
    expect(defs.SortState.properties?.direction.enum).toEqual([
      ...sortDirections
    ])
    expect(defs.CursorRequest.properties?.direction.enum).toEqual([
      ...cursorDirections
    ])
  })

  it('C-56 has a page mode and a cursor mode that exclude each other', () => {
    expect(schema.oneOf).toEqual([
      { $ref: '#/$defs/PageQuery' },
      { $ref: '#/$defs/CursorQuery' }
    ])
    expect(defs.PageQuery.not).toEqual({ required: ['cursor'] })
    expect(defs.CursorQuery.not).toEqual({ required: ['page'] })
  })

  it('C-58 search is optional and never empty', () => {
    expect(defs.QueryBase.required).not.toContain('search')
    expect(defs.QueryBase.properties?.search.minLength).toBe(1)
  })

  it('C-60 allows keys and rule properties it does not know', () => {
    expect(defs.QueryBase.additionalProperties).toBeUndefined()
    expect(defs.FilterRule.additionalProperties).toBe(true)
  })
})
