import process from 'node:process'

import js from '@eslint/js'
import { defineConfig, globalIgnores } from 'eslint/config'
import importPlugin from 'eslint-plugin-import-x'
import prettierRecommended from 'eslint-plugin-prettier/recommended'
import pluginVue from 'eslint-plugin-vue'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import vueEslintParser from 'vue-eslint-parser'

import layers from './scripts/eslint-layers.mjs'

// Variables are camelCase; tests may also use UPPER_CASE constants and
// PascalCase component stand-ins.
const namingConvention = variableFormats => [
  'error',
  {
    selector: 'variable',
    format: variableFormats
  },
  {
    selector: 'parameter',
    format: ['camelCase'],
    leadingUnderscore: 'allow'
  },
  {
    selector: 'memberLike',
    modifiers: ['private'],
    format: ['camelCase'],
    leadingUnderscore: 'require'
  },
  {
    selector: 'typeLike',
    format: ['PascalCase']
  }
]

// PRINCIPLES.md P1: the table renders, the consumer fetches and persists.
const p1Globals = [
  ...['fetch', 'XMLHttpRequest', 'WebSocket', 'EventSource'].map(name => ({
    name,
    message: 'The table does not fetch; the consumer does (P1).'
  })),
  ...['localStorage', 'sessionStorage', 'indexedDB'].map(name => ({
    name,
    message: 'The table does not persist state; the consumer does (P1).'
  }))
]
const p1Properties = [
  'fetch',
  'XMLHttpRequest',
  'localStorage',
  'sessionStorage',
  'indexedDB'
].flatMap(property =>
  ['window', 'globalThis', 'self'].map(object => ({
    object,
    property,
    message: 'No network or storage access in the library (P1).'
  }))
)

// The local evaluator works on UTF-16 code units with its own closed tables
// and its own calendar (docs/guide/semantics.md, profile tr-1). These APIs
// depend on the runtime, its Unicode version or its locale, walk code
// points, or let the engine roll an invalid day into a valid one.
const localUnits =
  'Iterate UTF-16 code units with an index (semantics.md#text).'
const localProperties = [
  ...[
    'normalize',
    'localeCompare',
    'toLowerCase',
    'toUpperCase',
    'toLocaleLowerCase',
    'toLocaleUpperCase',
    'trim',
    'trimStart',
    'trimEnd'
  ].map(property => ({
    property,
    message: 'tr-1 uses its own tables, not the runtime (semantics.md#text).'
  })),
  ...['codePointAt', 'fromCodePoint'].map(property => ({
    property,
    message: localUnits
  })),
  ...['UTC', 'parse'].map(property => ({
    object: 'Date',
    property,
    message: 'tr-1 checks and counts the calendar by hand (semantics.md#time).'
  }))
]

export default defineConfig([
  globalIgnores([
    'dist',
    'coverage',
    'temp',
    'fixtures',
    '.vitest',
    // shadcn-vue output: regenerated by the shadcn CLI, so it is not edited
    // to fit our style (knip skips it for the same reason).
    'apps/playground/skin/ui',
    'apps/playground/skin/lib/utils.ts',
    'apps/playground/dist',
    '.equivalence',
    'packages/*/dist'
  ]),
  {
    files: ['**/*.{js,mjs,ts,vue}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommendedTypeChecked,
      pluginVue.configs['flat/recommended'],
      // Last of the shared sets: turns off formatting rules that conflict
      // with prettier and adds the prettier/prettier rule.
      prettierRecommended
    ],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        projectService: true,
        extraFileExtensions: ['.vue']
      },
      globals: globals.browser
    },
    plugins: {
      '@typescript-eslint': tseslint.plugin,
      'import-x': importPlugin
    },
    rules: {
      'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
      'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' }
      ],
      'import-x/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal'],
          pathGroups: [
            {
              pattern: '@/**',
              group: 'internal'
            },
            // The package itself, imported by name in tests and the
            // playground. Without this the group depends on whether dist/
            // exists (self-reference through `exports`): internal after a
            // build, external on a fresh checkout.
            {
              pattern: '@dolusoft/query-table',
              group: 'internal'
            }
          ],
          pathGroupsExcludedImportTypes: ['builtin'],
          'newlines-between': 'always',
          alphabetize: {
            order: 'asc',
            caseInsensitive: true
          }
        }
      ],
      '@typescript-eslint/naming-convention': namingConvention(['camelCase']),
      'vue/singleline-html-element-content-newline': 'off',
      'vue/multiline-html-element-content-newline': 'off',
      'vue/no-multiple-template-root': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      eqeqeq: ['error', 'always'],
      curly: ['error', 'all'],
      '@typescript-eslint/no-shadow': 'error'
    }
  },
  {
    // Vue SFCs: vue-eslint-parser reads the template and hands <script> to
    // the TypeScript parser.
    files: ['**/*.vue'],
    languageOptions: {
      parser: vueEslintParser,
      parserOptions: {
        parser: tseslint.parser,
        projectService: true,
        extraFileExtensions: ['.vue']
      }
    }
  },
  {
    // Plain JavaScript (scripts, eslint.config.js) is outside tsconfig.json,
    // so it gets no type information. It runs in Node.
    files: ['**/*.{js,mjs}'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      parserOptions: { projectService: false },
      globals: globals.node
    }
  },
  {
    // Config files run in Node.
    files: ['*.config.ts', 'apps/playground/vite.config.ts'],
    languageOptions: { globals: globals.node }
  },
  {
    // Tests and the playground run in happy-dom or a real browser and may
    // read Node's `process`; specs sit next to the unit they cover.
    files: [
      'tests/**',
      'apps/playground/**',
      'packages/vue/src/**/*.spec.ts',
      'packages/*/tests/**'
    ],
    languageOptions: { globals: { ...globals.browser, ...globals.node } },
    rules: {
      '@typescript-eslint/naming-convention': namingConvention([
        'camelCase',
        'UPPER_CASE',
        'PascalCase'
      ])
    }
  },
  {
    // The v3 layers point one way (ADR 0003): the protocol imports nothing,
    // the core only the protocol and @tanstack/table-core, and a feature only
    // itself and shared/. Re-exports and dynamic imports count.
    files: ['packages/*/src/**/*.{ts,vue}'],
    ignores: ['packages/*/src/**/*.spec.ts'],
    plugins: { layers },
    rules: { 'layers/boundaries': 'error' }
  },
  {
    // A playground example is named after the feature it shows.
    files: ['apps/playground/examples/*.vue'],
    rules: { 'vue/multi-word-component-names': 'off' }
  },
  {
    // The library never depends on its test skin or test helpers. Unit specs
    // sit in src/ and may use tests/support/mount-table.
    files: ['packages/vue/src/**', 'contract/**'],
    ignores: ['packages/vue/src/**/*.spec.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                '**/tests/**',
                '**/tests',
                'tests/**',
                '**/playground/**',
                '**/playground'
              ],
              message:
                'Library code must not import from tests/ or playground/.'
            }
          ]
        }
      ]
    }
  },
  {
    // PRINCIPLES.md P1: the table renders, the consumer fetches and
    // persists. No network or storage access in any of the three packages.
    files: ['packages/*/src/**', 'contract/**'],
    ignores: ['packages/*/src/**/*.spec.ts'],
    rules: {
      'no-restricted-globals': ['error', ...p1Globals],
      'no-restricted-properties': ['error', ...p1Properties]
    }
  },
  {
    // The local evaluator: no runtime text or calendar API (tr-1). It
    // repeats the P1 entries, since a later block replaces a rule's options.
    files: ['packages/query-protocol/src/local/**/*.ts'],
    ignores: ['packages/query-protocol/src/local/**/*.spec.ts'],
    rules: {
      'no-restricted-globals': [
        'error',
        ...p1Globals,
        {
          name: 'Intl',
          message: 'tr-1 uses its own tables, not a locale (semantics.md#text).'
        }
      ],
      'no-restricted-properties': [
        'error',
        ...p1Properties,
        ...localProperties
      ],
      'no-restricted-syntax': [
        'error',
        { selector: 'ForOfStatement', message: localUnits }
      ]
    }
  }
])
