import process from 'node:process'

import js from '@eslint/js'
import { defineConfig, globalIgnores } from 'eslint/config'
import importPlugin from 'eslint-plugin-import-x'
import prettierRecommended from 'eslint-plugin-prettier/recommended'
import pluginVue from 'eslint-plugin-vue'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import vueEslintParser from 'vue-eslint-parser'

// Variables are camelCase; tests may also use UPPER_CASE constants and
// PascalCase component stand-ins.
const namingConvention = variableFormats => [
  'error',
  {
    selector: 'variable',
    format: variableFormats
  },
  {
    selector: 'parameter',
    format: ['camelCase'],
    leadingUnderscore: 'allow'
  },
  {
    selector: 'memberLike',
    modifiers: ['private'],
    format: ['camelCase'],
    leadingUnderscore: 'require'
  },
  {
    selector: 'typeLike',
    format: ['PascalCase']
  }
]

export default defineConfig([
  globalIgnores([
    'dist',
    'coverage',
    'temp',
    'fixtures',
    '.vitest',
    // shadcn-vue output: regenerated by the shadcn CLI, so it is not edited
    // to fit our style (knip skips it for the same reason).
    'tests/skin/ui',
    'tests/skin/lib/utils.ts'
  ]),
  {
    files: ['**/*.{js,mjs,ts,vue}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommendedTypeChecked,
      pluginVue.configs['flat/recommended'],
      // Last of the shared sets: turns off formatting rules that conflict
      // with prettier and adds the prettier/prettier rule.
      prettierRecommended
    ],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        projectService: true,
        extraFileExtensions: ['.vue']
      },
      globals: globals.browser
    },
    plugins: {
      '@typescript-eslint': tseslint.plugin,
      'import-x': importPlugin
    },
    rules: {
      'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
      'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' }
      ],
      'import-x/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal'],
          pathGroups: [
            {
              pattern: '@/**',
              group: 'internal'
            }
          ],
          pathGroupsExcludedImportTypes: ['builtin'],
          'newlines-between': 'always',
          alphabetize: {
            order: 'asc',
            caseInsensitive: true
          }
        }
      ],
      '@typescript-eslint/naming-convention': namingConvention(['camelCase']),
      'vue/singleline-html-element-content-newline': 'off',
      'vue/multiline-html-element-content-newline': 'off',
      'vue/no-multiple-template-root': 'off',
      // A column with `html: true` renders its text as markup by contract
      // (see contract/rules.md); that is the feature, not an oversight.
      'vue/no-v-html': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      eqeqeq: ['error', 'always'],
      curly: ['error', 'all'],
      '@typescript-eslint/no-shadow': 'error'
    }
  },
  {
    // Vue SFCs: vue-eslint-parser reads the template and hands <script> to
    // the TypeScript parser.
    files: ['**/*.vue'],
    languageOptions: {
      parser: vueEslintParser,
      parserOptions: {
        parser: tseslint.parser,
        projectService: true,
        extraFileExtensions: ['.vue']
      }
    }
  },
  {
    // Plain JavaScript (scripts, eslint.config.js) is outside tsconfig.json,
    // so it gets no type information. It runs in Node.
    files: ['**/*.{js,mjs}'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      parserOptions: { projectService: false },
      globals: globals.node
    }
  },
  {
    // Root config files run in Node.
    files: ['*.config.ts'],
    languageOptions: { globals: globals.node }
  },
  {
    // Tests run in happy-dom or a real browser and read Node's `process`;
    // specs sit next to the unit they cover.
    files: ['tests/**', 'src/**/*.spec.ts'],
    languageOptions: { globals: { ...globals.browser, ...globals.node } },
    rules: {
      '@typescript-eslint/naming-convention': namingConvention([
        'camelCase',
        'UPPER_CASE',
        'PascalCase'
      ])
    }
  },
  {
    // The library never depends on its test skin or test helpers. Unit specs
    // sit in src/ and may use tests/support/mount-table.
    files: ['src/**', 'contract/**'],
    ignores: ['src/**/*.spec.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/tests/**', '**/tests', 'tests/**'],
              message: 'Library code must not import from tests/.'
            }
          ]
        }
      ]
    }
  }
])
