import type {
  CursorQuery,
  FilterRule,
  FilterValue,
  PageCursors,
  TableQuery
} from '@dolusoft/query-table'

// A stand-in for a real server: it evaluates the query the table emits
// (filters, sort, page) over an in-memory list. The table never filters or
// sorts; this is the consumer's side of the contract.

const names = [
  'Charlie',
  'Alice',
  'Bob',
  'Dave',
  'Eve',
  'Frank',
  'Grace',
  'Heidi',
  'Ivan',
  'Judy',
  'Mallory',
  'Niaj',
  'Olivia',
  'Peggy',
  'Rupert'
]
const cities = ['Ankara', 'İstanbul', 'İzmir', 'Bursa', 'Antalya']

// Fixed fixtures, generated by the consumer, never by the library. Every
// call returns a fresh array with the same content.
export const createDemoRows = () =>
  Array.from({ length: 200 }, (_, i) => ({
    id: i + 1,
    name: names[i % names.length],
    city: cities[i % cities.length],
    age: 22 + ((i * 7) % 30),
    salary: 42000 + ((i * 3517) % 40000),
    joined: `2024-${String((i % 12) + 1).padStart(2, '0')}-${String((i % 27) + 1).padStart(2, '0')}`,
    active: i % 3 !== 0
  }))

export type DemoRow = ReturnType<typeof createDemoRows>[number]

const valueOf = (row: object, field: string): unknown =>
  field
    .split('.')
    .reduce<unknown>(
      (value, key) =>
        value && typeof value === 'object'
          ? (value as Record<string, unknown>)[key]
          : undefined,
      row
    )
// ISO dates compare chronologically; numbers and booleans compare as
// numbers. Text matching is case-insensitive, a policy of this demo server
// rather than of the table.
const normalize = (value: FilterValue) =>
  typeof value === 'string' ? value.toLowerCase() : Number(value)

const matches = (row: object, rule: FilterRule): boolean => {
  const raw = valueOf(row, rule.field)
  if (raw === undefined || raw === null) {
    return false
  }
  const value = normalize(raw as FilterValue)
  const expected = normalize(rule.value)
  const condition = rule.condition
  switch (condition) {
    case 'Contains':
      return String(value).includes(String(expected))
    case 'NotContains':
      return !String(value).includes(String(expected))
    case 'StartsWith':
      return String(value).startsWith(String(expected))
    case 'EndsWith':
      return String(value).endsWith(String(expected))
    case 'Equal':
      return value === expected
    case 'NotEqual':
      return value !== expected
    case 'GreaterThan':
      return value > expected
    case 'GreaterThanOrEqual':
      return value >= expected
    case 'LessThan':
      return value < expected
    case 'LessThanOrEqual':
      return value <= expected
    default: {
      const unhandled: never = condition
      throw new Error(`Unsupported demo filter condition: ${String(unhandled)}`)
    }
  }
}

/** The rows that pass `query.filters`, sorted by `query.sort`; not paged. */
export const filterDemoRows = <R extends object>(
  allRows: readonly R[],
  query: Pick<TableQuery, 'filters' | 'sort'>
): R[] => {
  const groups = new Map<string, FilterRule[]>()
  for (const rule of query.filters) {
    const group = groups.get(rule.field) ?? []
    group.push(rule)
    groups.set(rule.field, group)
  }
  const filtered = allRows.filter(row =>
    [...groups.values()].every(rules => {
      const negative = rules.every(
        rule =>
          rule.condition === 'NotEqual' || rule.condition === 'NotContains'
      )
      return negative
        ? rules.every(rule => matches(row, rule))
        : rules.some(rule => matches(row, rule))
    })
  )
  const sort = query.sort
  if (sort) {
    filtered.sort((a, b) => {
      const left = valueOf(a, sort.field)
      const right = valueOf(b, sort.field)
      const order =
        typeof left === 'number' && typeof right === 'number'
          ? left - right
          : String(left).localeCompare(String(right), 'en')
      return sort.direction === 'asc' ? order : -order
    })
  }
  return filtered
}

/** One page of the filtered and sorted rows, with the filtered total. */
export const queryDemoRows = <R extends object>(
  allRows: readonly R[],
  query: TableQuery
) => {
  const filtered = filterDemoRows(allRows, query)
  const offset = (query.page - 1) * query.pageSize
  return {
    rows: filtered.slice(offset, offset + query.pageSize),
    totalRows: filtered.length
  }
}

/**
 * Rows whose name or city holds the search text, case-insensitive: what this
 * demo server matches a global search against (the server decides, C-58).
 */
export const searchDemoRows = <R extends object>(
  rows: readonly R[],
  search: string | undefined
): R[] => {
  const needle = search?.trim().toLowerCase()
  if (!needle) {
    return [...rows]
  }
  return rows.filter(row =>
    ['name', 'city'].some(field => {
      const value = valueOf(row, field)
      return typeof value === 'string' && value.toLowerCase().includes(needle)
    })
  )
}

/**
 * One cursor page (C-56). A cursor is the base64 offset of the page it leads
 * to; the table never reads inside it. No total: a cursor server often does
 * not count.
 */
export const cursorDemoPage = <R extends object>(
  allRows: readonly R[],
  query: CursorQuery
) => {
  const matching = searchDemoRows(filterDemoRows(allRows, query), query.search)
  const offset = query.cursor ? Number(atob(query.cursor.token)) : 0
  const end = offset + query.pageSize
  const token = (at: number) => btoa(String(at))
  return {
    rows: matching.slice(offset, end),
    cursors: {
      next: end < matching.length ? token(end) : null,
      prev: offset > 0 ? token(Math.max(0, offset - query.pageSize)) : null
    } satisfies PageCursors
  }
}
