// Builds tests/skin/test-skin.css, the stylesheet of the browser tests.
//
//   theme.css         the theme the shadcn-vue CLI wrote (`shadcn-vue init`,
//                     style reka-nova, base color neutral). Not edited by hand:
//                     every color and radius comes from it.
//   mapping.css       the table's DOM contract mapped onto shadcn-vue class
//                     strings with `@apply`.
//
//   node tests/skin/gen-skin.ts          write test-skin.css
//   node tests/skin/gen-skin.ts --check  fail when test-skin.css is stale
//
// Two lines of the CLI output are replaced on purpose:
//   - the Google Fonts `@import url(...)`: tests must not need the network;
//   - `shadcn-vue/tailwind.css`: the CLI writes that import, but the package
//     ships no such file. The same file lives in the `shadcn` package.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const read = (path: string) => readFileSync(path, 'utf8').replace(/\r\n/g, '\n')

export const skinPath = join(here, 'test-skin.css')

export const buildSkin = (): string => {
  const theme = read(join(here, 'theme.css'))
    .replace(/^@import[^\n]*\n/gm, '')
    .trim()
  const mapping = read(join(here, 'mapping.css')).trim()
  return [
    '/* Test-only skin. Generated by tests/skin/gen-skin.ts; do not edit. */',
    '@import "tailwindcss";',
    '@import "tw-animate-css";',
    '@import "shadcn/tailwind.css";',
    '',
    theme,
    '',
    '/* ==== mapping.css ==== */',
    mapping,
    ''
  ].join('\n')
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  if (process.argv.includes('--check')) {
    let current = ''
    try {
      current = read(skinPath)
    } catch {
      // A missing file counts as stale.
    }
    if (current !== buildSkin()) {
      console.error(
        'test-skin.css is stale. Run `pnpm skin:gen` and commit it.'
      )
      process.exit(1)
    }
    console.log('test-skin.css is up to date')
  } else {
    writeFileSync(skinPath, buildSkin())
    console.log('wrote tests/skin/test-skin.css')
  }
}
